server:
  port: 9001

spring:
  application:
    name: bmm-outer-service-leo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.183.140:1521:orcl
    username: C##zgb
    password: 123456
    druid:
      web-stat-filter:
        enabled: false


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://192.168.183.140:7001/eureka
      # 集群版
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: outer-9001
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2


# 服务调用
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

htstrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 60000

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.leo.zu.entities    # 所有Entity别名类所在包


# 负载均衡
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 60000


# log config
logging:
  config:
    classpath: logback.xml


# SwaggerUI
mconfig:
  # 是否开启swagger接口文档
  swagger-ui-open: true


